name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies for all packages
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          rm -rf node_modules
          pnpm install --verbose

      - name: Build for ttoss-tech-blog
        run: |
          cd packages/ttoss-tech-blog
          pnpm build

      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: packages/ttoss-tech-blog/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://github.com/emayom/ttoss-monorepo
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
